import {initializeApp} from "https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js";
import {getFirestore,collection,addDoc,updateDoc,deleteDoc,doc,onSnapshot,serverTimestamp,writeBatch} from "https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";
import {createClient} from "https://esm.sh/@supabase/supabase-js@2.57.4";
import * as XLSX from "https://esm.sh/xlsx@0.18.5";
import jsQR from "https://esm.sh/jsqr@1.4.0";
import * as pdfjsLib from "https://esm.sh/pdfjs-dist@4.10.38/build/pdf.mjs";
pdfjsLib.GlobalWorkerOptions.workerSrc="https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.worker.min.mjs";

const firebaseConfig={apiKey:"AIzaSyAO5gy-53kCBWV-vxNQlrRvzIR-p-IIycg",authDomain:"ous-workera.firebaseapp.com",projectId:"ous-workera",storageBucket:"ous-workera.firebasestorage.app",messagingSenderId:"779373746855",appId:"1:779373746855:web:98ed38d9abb7ed45839982",measurementId:"G-MPK93DMFEC"};
const firebaseApp=initializeApp(firebaseConfig),db=getFirestore(firebaseApp);
const clientsRef=collection(db,"envioClientes"),shipmentsRef=collection(db,"envioRegistros");
const supabase=createClient("https://lwrsteqkxumjpdpycawa.supabase.co","sb_publishable_dc-w-dWxVusCsafPIgpaXw_BONFU0qU");
const SALES_DRIVE_URL="https://script.google.com/macros/s/AKfycbx0FY1PArGO2MVtCkRcqy-cvRnPqXPx1Fb8yNuTs9Mumj8RWJ4xGbvw0Nlj1GxSpchd5Q/exec";

const state={
  clients:JSON.parse(localStorage.getItem("we_clients")||"[]"),
  shipments:JSON.parse(localStorage.getItem("we_shipments")||"[]"),
  month:new Date(),
  clientPage:1,
  clientPageSize:20,
  saleCandidates:[]
};
const $=s=>document.querySelector(s);
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const normalize=v=>String(v??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
const save=()=>{localStorage.setItem("we_clients",JSON.stringify(state.clients));localStorage.setItem("we_shipments",JSON.stringify(state.shipments));};
const modal=(title,html,wide=false)=>{$("#modal-content").innerHTML=`<h2>${esc(title)}</h2>${html}`;$("#modal .modal-card").classList.toggle("wide",wide);$("#modal").classList.remove("hidden")};
const close=()=>$("#modal").classList.add("hidden");
const clientById=id=>state.clients.find(c=>String(c.id)===String(id));
const clientShipments=id=>state.shipments.filter(s=>String(s.clientId)===String(id)).sort((a,b)=>b.fecha.localeCompare(a.fecha));
const today=()=>new Date().toISOString().slice(0,10);
const whatsappNumber=value=>{let n=String(value||"").replace(/\D/g,"");if(n.length===9)n="51"+n;return n;};
const whatsappIcon='<svg class="whatsapp-icon" viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M12.04 2a9.84 9.84 0 0 0-8.42 14.93L2 22l5.2-1.58A9.9 9.9 0 1 0 12.04 2Zm0 17.98a8.1 8.1 0 0 1-4.13-1.13l-.3-.18-3.08.94.98-3-.2-.31a8.08 8.08 0 1 1 6.73 3.68Zm4.43-6.06c-.24-.12-1.44-.71-1.66-.79-.22-.08-.38-.12-.55.12-.16.24-.63.79-.77.95-.14.16-.28.18-.52.06-.24-.12-1.03-.38-1.96-1.21a7.35 7.35 0 0 1-1.36-1.69c-.14-.24-.02-.37.11-.49.11-.11.24-.28.36-.43.12-.14.16-.24.24-.4.08-.16.04-.3-.02-.43-.06-.12-.55-1.31-.75-1.8-.2-.47-.4-.41-.55-.42h-.46c-.16 0-.42.06-.65.3-.22.24-.85.83-.85 2.02 0 1.19.87 2.34.99 2.5.12.16 1.7 2.6 4.13 3.65.58.25 1.03.4 1.38.51.58.18 1.1.16 1.52.1.46-.07 1.44-.59 1.64-1.16.2-.57.2-1.06.14-1.16-.06-.1-.22-.16-.46-.28Z"/></svg>';
const setCloudStatus=(text,error=false)=>{const el=$("#cloud-status");if(el){el.classList.toggle("error",error);el.innerHTML=`<span class="status-dot"></span> ${esc(text)}`;}};
const firebaseError=error=>{console.error(error);setCloudStatus("Sin conexión",true);alert(error?.code?.includes("permission-denied")?"Firestore rechazó la operación. Debes publicar las reglas gratuitas incluidas en firestore.rules.":`No se pudo guardar en Firebase: ${error.message||error}`);};
onSnapshot(clientsRef,snapshot=>{state.clients=snapshot.docs.map(d=>({id:d.id,...d.data()}));save();render();setCloudStatus("Sincronizado");},firebaseError);
onSnapshot(shipmentsRef,snapshot=>{state.shipments=snapshot.docs.map(d=>({id:d.id,...d.data()}));save();render();setCloudStatus("Sincronizado");},firebaseError);

$("#modal-close").onclick=close;
document.querySelectorAll(".nav-item").forEach(b=>b.onclick=()=>show(b.dataset.view));
document.querySelectorAll("[data-view-link]").forEach(b=>b.onclick=()=>show(b.dataset.viewLink));
function show(v){document.querySelectorAll(".view").forEach(x=>x.classList.toggle("active",x.id===v));document.querySelectorAll(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.view===v));$("#page-title").textContent={dashboard:"Resumen",clientes:"Clientes y envíos",calendario:"Calendario"}[v];render();}

document.addEventListener("click",e=>{
  const a=e.target.closest("[data-action]");if(!a)return;
  if(a.dataset.action==="new-client") modal("Agregar cliente",`<form class="form" id="client-form"><label>RUC<input name="ruc" inputmode="numeric" maxlength="11" required placeholder="11 dígitos"></label><label>Razón social<input name="razon" required></label><label>Contacto / teléfono<input name="contacto" required></label><p class="form-help">Las series, tracking y PDF se agregan después, dentro de la ficha del cliente.</p><button>Guardar y abrir cliente</button></form>`);
  if(a.dataset.action==="bulk-clients") modal("Carga masiva de clientes",`<form class="form import-form" id="bulk-client-form"><div class="import-guide"><span class="import-icon">C</span><div><b>Prepara la primera hoja con estas columnas:</b><strong>RUC · RAZON SOCIAL · TELEFONO</strong><small>Ejemplo: +51 999-999-999 se guardará como 999999999.</small></div></div><div class="template-download"><div><b>¿No tienes el formato?</b><small>Descarga, completa y vuelve a subir esta plantilla.</small></div><button type="button" data-action="download-template" data-template="clients">↓ Descargar plantilla Excel</button></div><label class="file-field"><span>Selecciona tu archivo Excel completado</span><input name="file" type="file" accept=".xlsx,.xls,.csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel,text/csv" required></label><button>Importar clientes</button></form>`);
  if(a.dataset.action==="bulk-series") modal("Importar series por RUC",`<form class="form import-form" id="bulk-series-form"><div class="import-guide yellow"><span class="import-icon">S</span><div><b>Prepara la primera hoja con estas columnas:</b><strong>RUC · SERIE</strong><small>Puedes repetir el mismo RUC en varias filas. Cada serie se agregará al inventario general del cliente.</small></div></div><div class="template-download yellow"><div><b>¿No tienes el formato?</b><small>Descarga, completa y vuelve a subir esta plantilla.</small></div><button type="button" data-action="download-template" data-template="series">↓ Descargar plantilla Excel</button></div><label class="file-field"><span>Selecciona tu archivo Excel completado</span><input name="file" type="file" accept=".xlsx,.xls,.csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel,text/csv" required></label><button>Importar series</button></form>`);
  if(a.dataset.action==="review-sales")reviewSalesFromDrive();
  if(a.dataset.action==="open-client") openClient(a.dataset.id);
  if(a.dataset.action==="new-shipment") openShipmentForm(a.dataset.id);
  if(a.dataset.action==="new-sale") openSaleForm(a.dataset.id);
  if(a.dataset.action==="edit-sale") openSaleForm(a.dataset.client,a.dataset.sale);
  if(a.dataset.action==="copy-sale") copySale(a.dataset.client,a.dataset.sale);
  if(a.dataset.action==="delete-sale"&&confirm("¿Eliminar esta venta? Las series asociadas quedarán disponibles como ‘Sin venta’."))deleteSale(a.dataset.client,a.dataset.sale);
  if(a.dataset.action==="assign-sale-series")openAssignSaleSeries(a.dataset.client,a.dataset.sale);
  if(a.dataset.action==="assign-existing-series")openAssignExistingSeries(a.dataset.client,a.dataset.series);
  if(a.dataset.action==="edit-shipment") openShipmentForm(a.dataset.client,a.dataset.id);
  if(a.dataset.action==="open-file") openFile(a.dataset.id);
  if(a.dataset.action==="whatsapp") openWhatsApp(a.dataset.id);
  if(a.dataset.action==="delete-shipment"&&confirm("¿Eliminar este envío y su archivo adjunto?"))deleteShipment(a.dataset.id,a.dataset.client);
  if(a.dataset.action==="delete-client-series"&&confirm(`¿Quitar la serie ${a.dataset.series} de este cliente?`))deleteClientSeries(a.dataset.id,a.dataset.series);
  if(a.dataset.action==="toggle-sale-payment")toggleSalePayment(a.dataset.client,a.dataset.sale);
  if(a.dataset.action==="download-template")downloadTemplate(a.dataset.template);
  if(a.dataset.action==="client-page"){state.clientPage=Number(a.dataset.page)||1;renderClients();document.querySelector("#clientes .section-head")?.scrollIntoView({behavior:"smooth",block:"start"});}
  if(a.dataset.action==="close-import")close();
});

document.addEventListener("submit",async e=>{
  e.preventDefault();const f=new FormData(e.target);
  if(e.target.id==="bulk-client-form"){
    const file=f.get("file");if(!file?.size)return alert("Selecciona un archivo Excel.");
    await importClients(file);return;
  }
  if(e.target.id==="bulk-series-form"){
    const file=f.get("file");if(!file?.size)return alert("Selecciona un archivo Excel.");
    await importSeries(file);return;
  }
  if(e.target.id==="review-sales-form"){
    const file=f.get("file");if(!file?.size)return alert("Selecciona el archivo Excel descargado de Drive.");
    await reviewSalesFile(file);return;
  }
  if(e.target.id==="import-reviewed-sales-form"){
    const selected=f.getAll("saleKey").map(String);if(!selected.length)return alert("Selecciona por lo menos una venta.");
    await importReviewedSales(selected);return;
  }
  if(e.target.id==="series-form"){
    const clientId=String(f.get("clientId")),series=String(f.get("series")||"").trim(),client=clientById(clientId),current=clientSeries(client);
    if(!series)return alert("Escribe una serie.");
    if(current.some(value=>normalize(value)===normalize(series)))return alert("Esta serie ya está registrada para el cliente.");
    try{setCloudStatus("Guardando serie...");await updateDoc(doc(db,"envioClientes",clientId),{series:[...current,series],actualizadoEn:serverTimestamp()});close();setTimeout(()=>openClient(clientId),250);}catch(error){firebaseError(error);}return;
  }
  if(e.target.id==="sale-form"){
    const clientId=String(f.get("clientId")),saleId=String(f.get("saleId")||""),client=clientById(clientId),sales=clientSales(client),existing=sales.find(item=>String(item.id)===saleId),values={fecha:String(f.get("fecha")),detalle:String(f.get("detalle")||"").trim(),estadoPago:String(f.get("estadoPago"))==="pagado"?"pagado":"pendiente"};
    const ventas=existing?sales.map(item=>String(item.id)===saleId?{...item,...values}:item):[...sales,{id:crypto.randomUUID(),...values,series:[],creadoEn:new Date().toISOString()}];
    try{setCloudStatus(existing?"Actualizando venta...":"Guardando venta...");await updateDoc(doc(db,"envioClientes",clientId),{ventas,actualizadoEn:serverTimestamp()});close();setTimeout(()=>openClient(clientId),250);}catch(error){firebaseError(error);}return;
  }
  if(e.target.id==="sale-series-form"){
    const clientId=String(f.get("clientId")),saleId=String(f.get("saleId")),client=clientById(clientId),sales=clientSales(client),sale=sales.find(item=>String(item.id)===saleId);
    if(!sale)return alert("No se encontró la venta.");
    if(sale.estadoPago!=="pagado")return alert("Primero debes marcar la venta como pagada.");
    const requested=[...new Map(String(f.get("series")||"").split(/[\n,;]+/).map(value=>value.trim()).filter(Boolean).map(value=>[normalize(value),value])).values()];
    if(!requested.length)return alert("Agrega por lo menos una serie.");
    const assignedElsewhere=new Set(sales.filter(item=>String(item.id)!==saleId).flatMap(item=>item.series||[]).map(normalize)),conflicts=requested.filter(value=>assignedElsewhere.has(normalize(value)));
    if(conflicts.length)return alert(`Estas series ya pertenecen a otra venta: ${conflicts.join(", ")}.`);
    const saleSeries=[...new Map([...(sale.series||[]),...requested].map(value=>[normalize(value),value])).values()],allSeries=[...new Map([...clientSeries(client),...requested].map(value=>[normalize(value),value])).values()];
    const updatedSales=sales.map(item=>String(item.id)===saleId?{...item,series:saleSeries}:item);
    try{setCloudStatus("Asignando series...");await updateDoc(doc(db,"envioClientes",clientId),{series:allSeries,ventas:updatedSales,actualizadoEn:serverTimestamp()});close();setTimeout(()=>openClient(clientId),250);}catch(error){firebaseError(error);}return;
  }
  if(e.target.id==="existing-series-sale-form"){
    const clientId=String(f.get("clientId")),saleId=String(f.get("saleId")),series=String(f.get("series")),client=clientById(clientId),sales=clientSales(client),sale=sales.find(item=>String(item.id)===saleId);
    if(!sale||sale.estadoPago!=="pagado")return alert("Selecciona una venta pagada.");
    if(sales.some(item=>(item.series||[]).some(value=>normalize(value)===normalize(series))))return alert("Esta serie ya está asociada a una venta.");
    const ventas=sales.map(item=>String(item.id)===saleId?{...item,series:[...(item.series||[]),series]}:item);
    try{setCloudStatus("Asignando serie...");await updateDoc(doc(db,"envioClientes",clientId),{ventas,actualizadoEn:serverTimestamp()});close();setTimeout(()=>openClient(clientId),250);}catch(error){firebaseError(error);}return;
  }
  if(e.target.id==="client-form"){
    const ruc=String(f.get("ruc")).trim();
    if(!/^\d{11}$/.test(ruc))return alert("El RUC debe tener 11 dígitos.");
    if(state.clients.some(c=>c.ruc===ruc))return alert("Ya existe un cliente con este RUC.");
    try{setCloudStatus("Guardando...");const result=await addDoc(clientsRef,{ruc,razon:String(f.get("razon")).trim(),contacto:String(f.get("contacto")).trim(),series:[],ventas:[],creadoEn:serverTimestamp()});close();setTimeout(()=>openClient(result.id),250);}catch(error){firebaseError(error);}
  }
  if(e.target.id==="shipment-form"){
    const shipmentId=String(f.get("shipmentId")||""),existing=shipmentId?state.shipments.find(s=>String(s.id)===shipmentId):null,file=f.get("file");let documento=existing?.documento||null,newFilePath="";
    if(file&&file.size){
      const allowed=["application/pdf","image/jpeg","image/png","image/webp"];
      if(!allowed.includes(file.type))return alert("Adjunta un PDF o una imagen JPG, PNG o WEBP.");
      if(file.size>4*1024*1024)return alert("El archivo no debe superar 4 MB en esta versión.");
      try{setCloudStatus("Subiendo archivo...");const safeName=file.name.replace(/[^a-zA-Z0-9._-]/g,"_");const path=`${f.get("clientId")}/${Date.now()}-${crypto.randomUUID()}-${safeName}`;const {error}=await supabase.storage.from("workera-envios").upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;const {data}=supabase.storage.from("workera-envios").getPublicUrl(path);documento={nombre:file.name,tipo:file.type,url:data.publicUrl,path};newFilePath=path;}catch(error){firebaseError(error);return;}
    }
    const payload={clientId:String(f.get("clientId")),fecha:f.get("fecha"),serie:String(f.get("serie")||"").trim(),tracking:String(f.get("tracking")||"").trim(),nota:String(f.get("nota")||"").trim(),documento,actualizadoEn:serverTimestamp()};
    try{setCloudStatus("Guardando...");if(shipmentId){await updateDoc(doc(db,"envioRegistros",shipmentId),payload);if(newFilePath&&existing?.documento?.path&&existing.documento.path!==newFilePath)await supabase.storage.from("workera-envios").remove([existing.documento.path]);}else await addDoc(shipmentsRef,{...payload,creadoEn:serverTimestamp()});close();}catch(error){if(newFilePath)await supabase.storage.from("workera-envios").remove([newFilePath]);firebaseError(error);}
  }
});

function cleanExcelRow(row){const values={};for(const [key,value] of Object.entries(row))values[normalize(key).replace(/[^a-z0-9]/g,"")]=value;return values;}
function downloadTemplate(type){
  const clients=type==="clients",rows=clients?[["RUC","RAZON SOCIAL","TELEFONO"],["20123456789","EMPRESA DE EJEMPLO SAC","999999999"]]:[["RUC","SERIE"],["20123456789","EQ-000001"],["20123456789","EQ-000002"]];
  const sheet=XLSX.utils.aoa_to_sheet(rows);sheet["!cols"]=clients?[{wch:16},{wch:34},{wch:16}]:[{wch:16},{wch:24}];
  for(const address of Object.keys(sheet)){if(address.startsWith("!"))continue;sheet[address].t="s";sheet[address].z="@";}
  const workbook=XLSX.utils.book_new();XLSX.utils.book_append_sheet(workbook,sheet,clients?"Clientes":"Series");XLSX.writeFile(workbook,clients?"Plantilla_clientes_Workera.xlsx":"Plantilla_series_Workera.xlsx");
}
function cleanRuc(value){return String(value??"").replace(/\D/g,"");}
function cleanPhone(value){let digits=String(value??"").replace(/\D/g,"");if(digits.length===11&&digits.startsWith("51"))digits=digits.slice(2);else if(digits.length>9)digits=digits.slice(-9);return digits;}
async function importClients(file){
  try{
    setCloudStatus("Leyendo Excel...");
    const workbook=XLSX.read(await file.arrayBuffer(),{type:"array"}),sheet=workbook.Sheets[workbook.SheetNames[0]],rows=XLSX.utils.sheet_to_json(sheet,{defval:"",raw:false});
    if(!rows.length)return alert("El archivo no contiene clientes.");
    const existing=new Set(state.clients.map(c=>cleanRuc(c.ruc))),seen=new Set(),valid=[],errors=[];let duplicates=0;
    rows.forEach((source,index)=>{const row=cleanExcelRow(source),ruc=cleanRuc(row.ruc),razon=String(row.razonsocial??"").trim(),contacto=cleanPhone(row.telefono);const reasons=[];if(!/^\d{11}$/.test(ruc))reasons.push("RUC inválido");if(!razon)reasons.push("falta razón social");if(!/^9\d{8}$/.test(contacto))reasons.push("teléfono inválido");if(existing.has(ruc)||seen.has(ruc)){duplicates++;return;}if(reasons.length){errors.push(`Fila ${index+2}: ${reasons.join(", ")}`);return;}seen.add(ruc);valid.push({ruc,razon,contacto,series:[],ventas:[]});});
    if(!valid.length){showImportResult(0,duplicates,errors);return;}
    for(let start=0;start<valid.length;start+=450){const chunk=valid.slice(start,start+450),batch=writeBatch(db);chunk.forEach(client=>batch.set(doc(clientsRef),{...client,creadoEn:serverTimestamp()}));setCloudStatus(`Importando ${Math.min(start+chunk.length,valid.length)} de ${valid.length}...`);await batch.commit();}
    setCloudStatus("Sincronizado");showImportResult(valid.length,duplicates,errors);
  }catch(error){firebaseError(error);}
}
function showImportResult(imported,duplicates,errors){modal("Resultado de la importación",`<div class="import-result"><div><strong>${imported}</strong><span>Importados</span></div><div><strong>${duplicates}</strong><span>Duplicados</span></div><div><strong>${errors.length}</strong><span>Con errores</span></div></div>${errors.length?`<div class="import-errors"><b>Filas no importadas</b>${errors.slice(0,25).map(error=>`<span>${esc(error)}</span>`).join("")}${errors.length>25?`<small>Y ${errors.length-25} errores más.</small>`:""}</div>`:"<p class=\"form-help\">Todos los registros válidos se importaron correctamente.</p>"}<button class="primary dark" data-action="close-import">Aceptar</button>`);}
function clientSeries(client){return Array.isArray(client?.series)?client.series.filter(Boolean):[];}
function clientSales(client){return Array.isArray(client?.ventas)?client.ventas.filter(Boolean):[];}
async function importSeries(file){
  try{
    setCloudStatus("Leyendo series...");
    const workbook=XLSX.read(await file.arrayBuffer(),{type:"array"}),sheet=workbook.Sheets[workbook.SheetNames[0]],rows=XLSX.utils.sheet_to_json(sheet,{defval:"",raw:false});
    if(!rows.length)return alert("El archivo no contiene series.");
    const clientsByRuc=new Map(state.clients.map(client=>[cleanRuc(client.ruc),client])),pending=new Map(),errors=[];let duplicates=0,imported=0;
    rows.forEach((source,index)=>{const row=cleanExcelRow(source),ruc=cleanRuc(row.ruc),serie=String(row.serie??row.series??"").trim(),client=clientsByRuc.get(ruc);if(!/^\d{11}$/.test(ruc)){errors.push(`Fila ${index+2}: RUC inválido`);return;}if(!client){errors.push(`Fila ${index+2}: no existe un cliente con RUC ${ruc}`);return;}if(!serie){errors.push(`Fila ${index+2}: falta la serie`);return;}const current=pending.get(client.id)||clientSeries(client).slice();if(current.some(value=>normalize(value)===normalize(serie))){duplicates++;return;}current.push(serie);pending.set(client.id,current);imported++;});
    const entries=[...pending.entries()];for(let start=0;start<entries.length;start+=450){const chunk=entries.slice(start,start+450),batch=writeBatch(db);chunk.forEach(([clientId,series])=>batch.update(doc(db,"envioClientes",clientId),{series,actualizadoEn:serverTimestamp()}));setCloudStatus(`Guardando series para ${Math.min(start+chunk.length,entries.length)} de ${entries.length} clientes...`);await batch.commit();}
    setCloudStatus("Sincronizado");showImportResult(imported,duplicates,errors);
  }catch(error){firebaseError(error);}
}

function excelDate(value){if(typeof value==="number"){const parsed=XLSX.SSF.parse_date_code(value);if(parsed)return `${parsed.y}-${String(parsed.m).padStart(2,"0")}-${String(parsed.d).padStart(2,"0")}`;}const text=String(value??"").trim();const latin=text.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})/);if(latin)return `${latin[3]}-${latin[2].padStart(2,"0")}-${latin[1].padStart(2,"0")}`;const iso=text.match(/^(\d{4})-(\d{2})-(\d{2})/);return iso?`${iso[1]}-${iso[2]}-${iso[3]}`:"";}
function mergeContacts(current,incoming){const map=new Map();[...(Array.isArray(current)?current:[]),...incoming].forEach(contact=>{const clean={nombre:String(contact.nombre||"").trim(),apellido:String(contact.apellido||"").trim(),telefono:cleanPhone(contact.telefono),correo:String(contact.correo||"").trim().toLowerCase()},key=clean.correo||clean.telefono||normalize(`${clean.nombre} ${clean.apellido}`);if(key)map.set(key,{...(map.get(key)||{}),...clean});});return [...map.values()];}
async function reviewSalesFromDrive(){try{setCloudStatus("Consultando ventas de Drive...");const response=await fetch(`${SALES_DRIVE_URL}?t=${Date.now()}`,{cache:"no-store",redirect:"follow"});if(!response.ok)throw new Error(`Google respondió ${response.status}`);const data=await response.json(),rows=Array.isArray(data)?data:data.rows;if(!Array.isArray(rows))throw new Error("La respuesta no contiene la lista rows");const grouped=new Map();rows.forEach(source=>{const row=cleanExcelRow(source),ruc=cleanRuc(row.ruc),fecha=excelDate(row.fecha),empresa=String(row.empresa||"").trim(),sourceId=String(row.id||"").trim(),status=normalize(row.estado);if(!/^\d{11}$/.test(ruc)||!fecha||!empresa||status.includes("anulada"))return;const key=sourceId||`${ruc}|${fecha}|${normalize(row.descripcion)}`,contact={nombre:row.nombrecontacto,apellido:row.apellidocontacto,telefono:row.telefonocontacto,correo:row.correocontacto},existing=grouped.get(key);if(existing){existing.contactos=mergeContacts(existing.contactos,[contact]);return;}grouped.set(key,{key,sourceId,fecha,ruc,razon:empresa,detalle:String(row.descripcion||"").trim()||"Venta de equipos",estadoPago:status.includes("pendiente")?"pendiente":"pagado",contactos:mergeContacts([],[contact])});});const importedIds=new Set(state.clients.flatMap(client=>clientSales(client).map(sale=>String(sale.sourceId||""))).filter(Boolean)),latest=state.clients.flatMap(client=>clientSales(client).map(sale=>sale.fecha||"")).sort().pop()||"",candidates=[...grouped.values()].filter(item=>{if(item.sourceId&&importedIds.has(item.sourceId))return false;const client=state.clients.find(value=>cleanRuc(value.ruc)===item.ruc),same=client&&clientSales(client).some(sale=>sale.fecha===item.fecha&&normalize(sale.detalle)===normalize(item.detalle));return !same&&(!latest||item.fecha>=latest);}).sort((a,b)=>b.fecha.localeCompare(a.fecha));state.saleCandidates=candidates;setCloudStatus("Sincronizado");showSalesReview(candidates,latest);}catch(error){console.error(error);setCloudStatus("No se pudo consultar Drive",true);alert("No se pudo leer la hoja de Drive. Verifica que la aplicación web de Apps Script esté implementada para ‘Cualquier usuario’ y que la URL corresponda a la versión más reciente.");}}
async function reviewSalesFile(file){try{setCloudStatus("Revisando ventas...");const workbook=XLSX.read(await file.arrayBuffer(),{type:"array",cellDates:false}),sheetName=workbook.SheetNames.find(name=>normalize(name).replace(/\s/g,"")==="egresoov")||workbook.SheetNames.find(name=>normalize(name).includes("egreso"));if(!sheetName)return alert("No se encontró la pestaña EGRESO OV.");const matrix=XLSX.utils.sheet_to_json(workbook.Sheets[sheetName],{header:1,defval:"",raw:true}),headerIndex=matrix.findIndex(row=>{const keys=row.map(value=>normalize(value).replace(/[^a-z0-9]/g,""));return keys.includes("id")&&keys.includes("fecha")&&keys.includes("empresa")&&keys.includes("ruc");});if(headerIndex<0)return alert("No se encontraron las columnas ID, FECHA, EMPRESA y RUC.");const headers=matrix[headerIndex].map(value=>normalize(value).replace(/[^a-z0-9]/g,"")),grouped=new Map();matrix.slice(headerIndex+1).forEach((values,index)=>{const row={};headers.forEach((key,column)=>{if(key)row[key]=values[column]??"";});const ruc=cleanRuc(row.ruc),fecha=excelDate(row.fecha),empresa=String(row.empresa||"").trim(),sourceId=String(row.id||"").trim(),status=normalize(row.estado);if(!ruc||!fecha||!empresa||status.includes("anulada"))return;const key=sourceId||`${ruc}|${fecha}|${normalize(row.factura||row.ov||row.descripcion)}`,contact={nombre:row.nombrecontacto,apellido:row.apellidocontacto,telefono:row.telefonocontacto,correo:row.correocontacto},existing=grouped.get(key);if(existing){existing.contactos=mergeContacts(existing.contactos,[contact]);return;}grouped.set(key,{key,sourceId,fecha,ruc,razon:empresa,detalle:String(row.descripcion||"").trim()||`Venta ${String(row.factura||row.ov||"").trim()}`.trim(),estadoPago:status.includes("pendiente")?"pendiente":"pagado",contactos:mergeContacts([], [contact]),fila:headerIndex+index+2});});const importedIds=new Set(state.clients.flatMap(client=>clientSales(client).map(sale=>String(sale.sourceId||""))).filter(Boolean)),latest=state.clients.flatMap(client=>clientSales(client).map(sale=>sale.fecha||"")).sort().pop()||"",candidates=[...grouped.values()].filter(item=>{if(item.sourceId&&importedIds.has(item.sourceId))return false;const client=state.clients.find(value=>cleanRuc(value.ruc)===item.ruc),same=client&&clientSales(client).some(sale=>sale.fecha===item.fecha&&normalize(sale.detalle)===normalize(item.detalle));return !same&&(!latest||item.fecha>=latest);}).sort((a,b)=>b.fecha.localeCompare(a.fecha));state.saleCandidates=candidates;setCloudStatus("Sincronizado");showSalesReview(candidates,latest);}catch(error){console.error(error);setCloudStatus("No se pudo leer el Excel",true);alert(`No se pudo revisar el archivo: ${error.message||error}`);}}
function showSalesReview(items,latest){modal("Nuevas ventas encontradas",items.length?`<form class="form" id="import-reviewed-sales-form"><p class="form-help">Se encontraron <b>${items.length}</b> ventas posteriores al corte ${latest?formatDate(latest):"inicial"}. Desmarca las que no quieras importar.</p><div class="sales-review-list">${items.map(item=>{const exists=state.clients.some(c=>cleanRuc(c.ruc)===item.ruc);return `<label class="sales-review-row"><input type="checkbox" name="saleKey" value="${esc(item.key)}" checked><span><b>${formatDate(item.fecha)} · ${esc(item.razon)}</b><small>RUC ${esc(item.ruc)} · ${exists?"Cliente existente":"Cliente nuevo"} · ${item.estadoPago==="pendiente"?"Pendiente":"Pagado"}</small></span></label>`;}).join("")}</div><button>Importar ventas seleccionadas</button></form>`:`<div class="sales-empty">No se encontraron ventas nuevas respecto de las que ya existen en el sistema.</div><button class="primary dark" data-action="close-import">Aceptar</button>`,true);}
async function importReviewedSales(keys){try{const chosen=state.saleCandidates.filter(item=>keys.includes(item.key)),byRuc=new Map();chosen.forEach(item=>{const list=byRuc.get(item.ruc)||[];list.push(item);byRuc.set(item.ruc,list);});const batch=writeBatch(db);for(const [ruc,items] of byRuc){const client=state.clients.find(value=>cleanRuc(value.ruc)===ruc),contacts=mergeContacts(client?.contactos,items.flatMap(item=>item.contactos)),newSales=items.map(item=>({id:crypto.randomUUID(),sourceId:item.sourceId||item.key,fecha:item.fecha,detalle:item.detalle,estadoPago:item.estadoPago,series:[],creadoEn:new Date().toISOString()})),primaryPhone=contacts.find(c=>c.telefono)?.telefono||client?.contacto||"",primaryEmail=contacts.find(c=>c.correo)?.correo||client?.correo||"";if(client)batch.update(doc(db,"envioClientes",client.id),{ventas:[...clientSales(client),...newSales],contactos:contacts,contacto:primaryPhone,correo:primaryEmail,actualizadoEn:serverTimestamp()});else batch.set(doc(clientsRef),{ruc,razon:items[0].razon,contacto:primaryPhone,correo:primaryEmail,contactos:contacts,series:[],ventas:newSales,creadoEn:serverTimestamp()});}setCloudStatus("Importando ventas...");await batch.commit();state.saleCandidates=[];setCloudStatus("Sincronizado");modal("Importación completada",`<div class="import-result"><div><strong>${chosen.length}</strong><span>Ventas importadas</span></div><div><strong>${[...byRuc].filter(([ruc])=>!state.clients.some(c=>cleanRuc(c.ruc)===ruc)).length}</strong><span>Clientes nuevos</span></div><div><strong>${[...byRuc].filter(([ruc])=>state.clients.some(c=>cleanRuc(c.ruc)===ruc)).length}</strong><span>Clientes existentes</span></div></div><button class="primary dark" data-action="close-import">Aceptar</button>`);}catch(error){firebaseError(error);}}

document.addEventListener("change",async e=>{
  if(e.target.id==="client-page-size"){state.clientPageSize=Number(e.target.value)||20;state.clientPage=1;renderClients();return;}
  if(e.target.name!=="file"||e.target.form?.id!=="shipment-form")return;
  const file=e.target.files?.[0],status=$("#qr-status"),tracking=e.target.form.elements.tracking;
  if(!file){status.textContent="";return;}
  status.className="qr-status scanning";status.textContent="Buscando código QR...";
  try{const raw=await scanQrFromFile(file);if(raw){tracking.value=extractTracking(raw);status.className="qr-status success";status.textContent=`QR detectado: ${tracking.value}`;}else{status.className="qr-status warning";status.textContent="No se encontró un QR legible. Puedes escribir el tracking manualmente.";}}catch(error){console.error(error);status.className="qr-status warning";status.textContent="No se pudo leer el QR. Puedes escribir el tracking manualmente.";}
});

async function scanQrFromFile(file){
  if(file.type==="application/pdf"){
    const pdf=await pdfjsLib.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;
    for(let pageNumber=1;pageNumber<=Math.min(pdf.numPages,5);pageNumber++){
      const page=await pdf.getPage(pageNumber),viewport=page.getViewport({scale:2.2}),canvas=document.createElement("canvas"),ctx=canvas.getContext("2d",{willReadFrequently:true});
      canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);await page.render({canvasContext:ctx,viewport}).promise;
      const found=scanCanvas(ctx,canvas.width,canvas.height);if(found)return found;
    }
    return null;
  }
  const bitmap=await createImageBitmap(file),max=2400,scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement("canvas"),ctx=canvas.getContext("2d",{willReadFrequently:true});
  canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return scanCanvas(ctx,canvas.width,canvas.height);
}
function scanCanvas(ctx,width,height){const pixels=ctx.getImageData(0,0,width,height),result=jsQR(pixels.data,width,height,{inversionAttempts:"attemptBoth"});return result?.data?.trim()||null;}
function extractTracking(raw){
  const text=String(raw).trim();
  try{const url=new URL(text);for(const key of ["tracking","track","guia","guide","codigo","code","numero","number","id"]){const value=url.searchParams.get(key);if(value)return value.trim();}const parts=url.pathname.split("/").filter(Boolean).reverse();const part=parts.find(v=>/^[a-z0-9._-]{6,}$/i.test(v));if(part)return decodeURIComponent(part);}catch{}
  if(/^[a-z0-9._-]{5,}$/i.test(text))return text;
  const candidates=text.match(/[a-z0-9][a-z0-9._-]{5,}/gi)||[];return candidates.sort((a,b)=>b.length-a.length)[0]||text;
}

function openFile(id){const s=state.shipments.find(x=>String(x.id)===String(id)),url=s?.documento?.url||s?.documento?.datos;if(!url)return alert("Este envío no tiene un archivo adjunto.");window.open(url,"_blank","noopener");}
async function deleteShipment(id,clientId){try{const s=state.shipments.find(x=>String(x.id)===String(id));setCloudStatus("Eliminando...");if(s?.documento?.path){const {error}=await supabase.storage.from("workera-envios").remove([s.documento.path]);if(error)throw error;}await deleteDoc(doc(db,"envioRegistros",String(id)));close();}catch(error){firebaseError(error);}}
async function deleteClientSeries(clientId,series){try{const client=clientById(clientId),next=clientSeries(client).filter(value=>normalize(value)!==normalize(series));setCloudStatus("Actualizando series...");await updateDoc(doc(db,"envioClientes",String(clientId)),{series:next,actualizadoEn:serverTimestamp()});close();setTimeout(()=>openClient(clientId),250);}catch(error){firebaseError(error);}}
function openSaleForm(clientId,saleId=""){const c=clientById(clientId),sale=saleId?clientSales(c).find(item=>String(item.id)===String(saleId)):null;if(!c)return;modal(`${sale?"Editar":"Nueva"} venta · ${c.razon}`,`<form class="form" id="sale-form"><input type="hidden" name="clientId" value="${c.id}"><input type="hidden" name="saleId" value="${esc(sale?.id||"")}"><div class="client-summary"><b>${esc(c.razon)}</b><span>RUC ${esc(c.ruc)} · Puedes corregir fecha, descripción y pago sin alterar sus series.</span></div><label>Fecha de venta<input name="fecha" type="date" value="${esc(sale?.fecha||today())}" required></label><label>Descripción de la venta<input name="detalle" value="${esc(sale?.detalle||"")}" placeholder="Ej. 2 equipos biométricos (opcional)"></label><label>Estado del pago<select name="estadoPago" required><option value="pendiente" ${sale?.estadoPago!=="pagado"?"selected":""}>Pendiente de pago</option><option value="pagado" ${sale?.estadoPago==="pagado"?"selected":""}>Pagado</option></select></label><button>${sale?"Guardar cambios":"Guardar nueva venta"}</button></form>`);}
function openAssignSaleSeries(clientId,saleId){const c=clientById(clientId),sale=clientSales(c).find(item=>String(item.id)===String(saleId));if(!c||!sale)return;if(sale.estadoPago!=="pagado")return alert("Primero debes marcar la venta como pagada.");const sales=clientSales(c),assignedOther=new Set(sales.filter(item=>String(item.id)!==String(saleId)).flatMap(item=>item.series||[]).map(normalize)),current=new Set((sale.series||[]).map(normalize)),available=clientSeries(c).filter(value=>!assignedOther.has(normalize(value))&&!current.has(normalize(value)));modal(`Asignar series · ${c.razon}`,`<form class="form" id="sale-series-form"><input type="hidden" name="clientId" value="${c.id}"><input type="hidden" name="saleId" value="${esc(sale.id)}"><div class="client-summary"><b>${esc(sale.detalle)||"Venta de equipos"}</b><span>${formatDate(sale.fecha)} · Pago confirmado</span></div>${available.length?`<div class="available-series"><b>Series disponibles sin venta</b><span>${available.map(esc).join(" · ")}</span></div>`:""}<label>Series para esta venta<textarea name="series" rows="5" required placeholder="Una serie por línea&#10;EQ-000101&#10;EQ-000102"></textarea><small>Puedes escribir una serie disponible de la lista o una nueva. Separa varias con saltos de línea, comas o punto y coma.</small></label><button>Asignar series a la venta</button></form>`);}
function openAssignExistingSeries(clientId,series){const c=clientById(clientId),paid=clientSales(c).filter(sale=>sale.estadoPago==="pagado");if(!c)return;if(!paid.length)return alert("Primero registra una venta y márcala como pagada para poder asignar esta serie.");modal(`Asignar serie · ${series}`,`<form class="form" id="existing-series-sale-form"><input type="hidden" name="clientId" value="${c.id}"><input type="hidden" name="series" value="${esc(series)}"><div class="client-summary"><b>${esc(series)}</b><span>${esc(c.razon)} · Selecciona la venta pagada correspondiente.</span></div><label>Venta<select name="saleId" required><option value="">Selecciona una venta</option>${paid.map(sale=>`<option value="${esc(sale.id)}">${formatDate(sale.fecha)} · ${esc(sale.detalle)||"Venta de equipos"}</option>`).join("")}</select></label><button>Asignar serie a la venta</button></form>`);}
async function toggleSalePayment(clientId,saleId){try{const client=clientById(clientId),ventas=clientSales(client).map(sale=>String(sale.id)===String(saleId)?{...sale,estadoPago:sale.estadoPago==="pagado"?"pendiente":"pagado"}:sale);setCloudStatus("Actualizando pago...");await updateDoc(doc(db,"envioClientes",String(clientId)),{ventas,actualizadoEn:serverTimestamp()});close();setTimeout(()=>openClient(clientId),250);}catch(error){firebaseError(error);}}
async function deleteSale(clientId,saleId){try{const client=clientById(clientId),sale=clientSales(client).find(item=>String(item.id)===String(saleId));if(!client||!sale)return;const ventas=clientSales(client).filter(item=>String(item.id)!==String(saleId)),ventasEliminadas=[...new Set([...(client.ventasEliminadas||[]),...(sale.sourceId?[String(sale.sourceId)]:[])])];setCloudStatus("Eliminando venta...");await updateDoc(doc(db,"envioClientes",String(clientId)),{ventas,ventasEliminadas,actualizadoEn:serverTimestamp()});close();setTimeout(()=>openClient(clientId),250);}catch(error){firebaseError(error);}}
async function copySale(clientId,saleId){const c=clientById(clientId),sale=clientSales(c).find(item=>String(item.id)===String(saleId));if(!c||!sale)return;const series=(sale.series||[]).join(", ")||"Sin serie asignada",text=`FECHA DE VENTA: ${formatDate(sale.fecha)}\nRUC: ${c.ruc}\nRAZÓN SOCIAL: ${c.razon}\nSERIE: ${series}`;try{await navigator.clipboard.writeText(text);alert("Venta copiada al portapapeles.");}catch{const area=document.createElement("textarea");area.value=text;document.body.append(area);area.select();document.execCommand("copy");area.remove();alert("Venta copiada al portapapeles.");}}
function openWhatsApp(clientId){const c=clientById(clientId),number=whatsappNumber(c?.contacto);if(number.length<9)return alert("El contacto de este cliente no contiene un número de WhatsApp válido.");const message=encodeURIComponent(`Hola, ${c.razon}. Le escribimos de Workera respecto a su envío.`);window.open(`https://wa.me/${number}?text=${message}`,"_blank","noopener");}
function openShipmentForm(clientId,shipmentId=""){const c=clientById(clientId),s=shipmentId?state.shipments.find(x=>String(x.id)===String(shipmentId)):null,series=clientSeries(c);if(!c)return;modal(`${s?"Editar":"Nuevo"} envío · ${c.razon}`,`<form class="form" id="shipment-form"><input type="hidden" name="clientId" value="${c.id}"><input type="hidden" name="shipmentId" value="${esc(s?.id||"")}"><div class="client-summary"><b>${esc(c.razon)}</b><span>RUC ${esc(c.ruc)} · ${esc(c.contacto)}</span></div><label>Fecha en que se envió<input name="fecha" type="date" value="${esc(s?.fecha||today())}" required></label><label>Serie enviada<input name="serie" list="client-series-options" value="${esc(s?.serie||"")}" placeholder="Selecciona o escribe la serie"><small>Esta serie corresponde específicamente a este envío.</small></label><datalist id="client-series-options">${series.map(value=>`<option value="${esc(value)}">`).join("")}</datalist><label>Tracking / guía<input name="tracking" value="${esc(s?.tracking||"")}" placeholder="Se completará al detectar el QR"></label><label>${s?.documento?"Reemplazar imagen o PDF (opcional)":"Adjuntar imagen o PDF"}<input name="file" type="file" accept="application/pdf,image/jpeg,image/png,image/webp"><small>${s?.documento?`Archivo actual: ${esc(s.documento.nombre)}. Solo se reemplazará si eliges otro. `:""}Al seleccionar uno se leerá automáticamente el QR. Máximo 4 MB.</small></label><div id="qr-status" class="qr-status"></div><label>Observación<textarea name="nota" rows="3" placeholder="Opcional">${esc(s?.nota||"")}</textarea></label><button>${s?"Guardar cambios":"Guardar envío"}</button></form>`);}
function openClient(id){const c=clientById(id);if(!c)return;const list=clientShipments(id),series=clientSeries(c),sales=clientSales(c).slice().sort((a,b)=>String(b.fecha||"").localeCompare(String(a.fecha||""))),pending=sales.filter(sale=>sale.estadoPago!=="pagado").length;modal(c.razon,`<div class="client-header"><div><span class="label">RUC</span><b>${esc(c.ruc)}</b></div><div><span class="label">CONTACTOS</span>${contactDetails(c)}</div><div class="client-actions"><button class="whatsapp-btn" data-action="whatsapp" data-id="${c.id}">${whatsappIcon} WhatsApp</button><button class="primary dark" data-action="new-shipment" data-id="${c.id}">+ Agregar envío</button></div></div><section class="sales-section"><div class="sales-heading"><div><span class="equipment-kicker">CONTROL COMERCIAL</span><h3>Ventas de equipos</h3><p>Registra la venta, confirma el pago y luego asigna sus series.</p></div><div class="sales-heading-actions"><span class="pending-total">${pending} pendientes</span><button class="primary dark" data-action="new-sale" data-id="${c.id}">+ Nueva venta</button></div></div><div class="sales-list">${sales.map(sale=>saleRow(sale,c)).join("")||'<div class="sales-empty">Todavía no hay ventas registradas. Las series aparecerán debajo para asociarlas cuando corresponda.</div>'}</div></section><section class="equipment-section"><div class="equipment-heading"><div><span class="equipment-kicker">INVENTARIO DEL CLIENTE</span><h3>Todas las series</h3><p>Consulta cuáles tienen una venta asociada y asigna las que todavía están libres.</p></div><span class="series-total">${series.length}</span></div><form id="series-form" class="series-inline"><input type="hidden" name="clientId" value="${c.id}"><input name="series" placeholder="Agregar una nueva serie" autocomplete="off" required><button>+ Agregar serie</button></form><div class="series-inventory">${series.map(value=>inventorySeriesRow(value,c,sales)).join("")||'<span class="series-empty">Este cliente todavía no tiene series registradas.</span>'}</div></section><h3 class="subheading">Historial de envíos</h3><div class="shipment-list">${list.map(s=>shipmentRow(s,c,true)).join("")||'<div class="empty">Todavía no hay envíos registrados para este cliente.</div>'}</div>`,true);}
function contactDetails(c){const contacts=Array.isArray(c.contactos)&&c.contactos.length?c.contactos:[{telefono:c.contacto,correo:c.correo}];return `<div class="contact-list">${contacts.map(contact=>`<span><b>${esc(`${contact.nombre||""} ${contact.apellido||""}`.trim())||"Contacto"}</b><small>${esc(contact.telefono||"")}${contact.telefono&&contact.correo?" · ":""}${esc(contact.correo||"")}</small></span>`).join("")}</div>`;}
function inventorySeriesRow(value,c,sales){const sale=sales.find(item=>(item.series||[]).some(series=>normalize(series)===normalize(value)));return `<div class="inventory-series-row"><b>${esc(value)}</b>${sale?`<span class="series-sale-status linked">${formatDate(sale.fecha)} · ${esc(sale.detalle)||"Venta asociada"}</span>`:`<span class="series-sale-status free">Sin venta</span><button data-action="assign-existing-series" data-client="${c.id}" data-series="${esc(value)}">Asignar a venta</button><button class="remove-series-btn" title="Quitar serie" data-action="delete-client-series" data-id="${c.id}" data-series="${esc(value)}">×</button>`}</div>`;}
function saleRow(sale,c){const paid=sale.estadoPago==="pagado",series=Array.isArray(sale.series)?sale.series:[];return `<article class="sale-row"><div class="sale-main"><div><span class="label">FECHA DE VENTA</span><b>${formatDate(sale.fecha)}</b></div><div><span class="label">DETALLE</span><b>${esc(sale.detalle)||"Venta de equipos"}</b></div><span class="payment-badge ${paid?"paid":"pending"}">${paid?"Pagado":"Pendiente"}</span></div><div class="sale-series"><span class="label">SERIES DE ESTA VENTA</span><div class="series-chips">${series.map(value=>`<span class="series-chip sale"><b>${esc(value)}</b></span>`).join("")||'<span class="series-empty">Sin series asignadas</span>'}</div></div><div class="sale-controls"><button class="edit-sale-btn" data-action="edit-sale" data-client="${c.id}" data-sale="${esc(sale.id)}">Editar venta</button><button class="edit-sale-btn" data-action="copy-sale" data-client="${c.id}" data-sale="${esc(sale.id)}">Copiar venta</button><button class="delete-sale-btn" data-action="delete-sale" data-client="${c.id}" data-sale="${esc(sale.id)}">Eliminar venta</button><button class="payment-toggle ${paid?"paid":""}" data-action="toggle-sale-payment" data-client="${c.id}" data-sale="${esc(sale.id)}">${paid?"Marcar pendiente":"Marcar como pagado"}</button>${paid?`<button class="assign-series-btn" data-action="assign-sale-series" data-client="${c.id}" data-sale="${esc(sale.id)}">+ Asignar series</button>`:'<span class="sale-waiting">Confirma el pago para asignar series</span>'}</div></article>`;}
function shipmentRow(s,c,actions=false){const isImage=s.documento?.tipo?.startsWith("image/");return `<article class="shipment-row"><div class="shipment-date"><b>${formatDate(s.fecha)}</b><span>${esc(s.serie)||"Sin serie"}</span></div><div><span class="label">TRACKING</span><b>${esc(s.tracking)||"Sin tracking"}</b><small>${esc(s.nota)||""}</small></div><div><span class="label">ARCHIVO</span>${s.documento?`<button class="link-btn" data-action="open-file" data-id="${s.id}">${isImage?"🖼️":"📄"} ${esc(s.documento.nombre)}</button>`:"<span>Sin archivo</span>"}</div>${actions?`<div class="shipment-actions"><button class="edit-link" data-action="edit-shipment" data-id="${s.id}" data-client="${c.id}">Editar</button><button class="danger-link" data-action="delete-shipment" data-id="${s.id}" data-client="${c.id}">Eliminar</button></div>`:""}</article>`;}

$("#client-search").addEventListener("input",()=>{state.clientPage=1;renderClients();});
$("#calendar-search").addEventListener("input",renderCalendar);
$("#prev-month").onclick=()=>{state.month=new Date(state.month.getFullYear(),state.month.getMonth()-1,1);renderCalendar();};
$("#next-month").onclick=()=>{state.month=new Date(state.month.getFullYear(),state.month.getMonth()+1,1);renderCalendar();};
$("#today").onclick=()=>{state.month=new Date();renderCalendar();};

function render(){renderClients();renderCalendar();renderDashboard();}
function renderClients(){const q=normalize($("#client-search")?.value),filtered=state.clients.filter(c=>normalize(`${c.ruc} ${c.razon} ${c.contacto} ${clientSeries(c).join(" ")}`).includes(q)),totalPages=Math.max(1,Math.ceil(filtered.length/state.clientPageSize));state.clientPage=Math.min(Math.max(1,state.clientPage),totalPages);const start=(state.clientPage-1)*state.clientPageSize,visible=filtered.slice(start,start+state.clientPageSize),rows=visible.map(c=>{const ss=clientShipments(c.id),series=clientSeries(c),sales=clientSales(c),pending=sales.filter(sale=>sale.estadoPago!=="pagado").length;return `<tr><td data-label="RUC">${esc(c.ruc)}</td><td data-label="Razón social"><b>${esc(c.razon)}</b></td><td data-label="Contacto">${esc(c.contacto)}</td><td data-label="Series"><span class="count series-count">${series.length}</span></td><td data-label="Ventas / pago"><span class="sales-cell"><b>${sales.length} ventas</b><small class="${pending?"has-pending":""}">${pending?pending+" pendientes":"Todo pagado"}</small></span></td><td data-label="Envíos"><span class="count">${ss.length}</span></td><td data-label="Último envío">${ss[0]?formatDate(ss[0].fecha):"—"}</td><td class="row-actions"><button class="whatsapp-mini" title="Abrir WhatsApp" aria-label="Abrir WhatsApp de ${esc(c.razon)}" data-action="whatsapp" data-id="${c.id}">${whatsappIcon}</button><button class="ghost action" data-action="open-client" data-id="${c.id}">Abrir ficha →</button></td></tr>`;}).join("");$("#clients-table").innerHTML=rows||'<tr><td colspan="8" class="empty">No se encontraron clientes.</td></tr>';renderClientPagination(filtered.length,totalPages,start,visible.length);}
function renderClientPagination(total,totalPages,start,visible){const el=$("#clients-pagination");if(!el)return;const from=total?start+1:0,to=start+visible;el.innerHTML=`<div class="pagination-summary">Mostrando <b>${from}–${to}</b> de <b>${total}</b> clientes</div><div class="pagination-actions"><label>Por página <select id="client-page-size"><option value="10" ${state.clientPageSize===10?"selected":""}>10</option><option value="20" ${state.clientPageSize===20?"selected":""}>20</option><option value="50" ${state.clientPageSize===50?"selected":""}>50</option></select></label><button data-action="client-page" data-page="${state.clientPage-1}" ${state.clientPage===1?"disabled":""}>‹ Anterior</button><span>Página <b>${state.clientPage}</b> de ${totalPages}</span><button data-action="client-page" data-page="${state.clientPage+1}" ${state.clientPage===totalPages?"disabled":""}>Siguiente ›</button></div>`;}
function renderDashboard(){const now=new Date(),prefix=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}`;$("#stat-clients").textContent=state.clients.length;$("#stat-shipments").textContent=state.shipments.length;$("#stat-month").textContent=state.shipments.filter(s=>s.fecha.startsWith(prefix)).length;$("#stat-pdf").textContent=state.shipments.filter(s=>s.documento).length;const latest=state.shipments.slice().sort((a,b)=>b.fecha.localeCompare(a.fecha)).slice(0,5);$("#recent-list").innerHTML=latest.map(s=>{const c=clientById(s.clientId)||{};return shipmentRow(s,c);}).join("")||'<div class="empty">No hay envíos registrados.</div>';}
function matchesShipment(s,q){const c=clientById(s.clientId)||{};return normalize(`${c.ruc} ${c.razon} ${c.contacto} ${clientSeries(c).join(" ")} ${s.serie} ${s.tracking} ${s.nota}`).includes(q);}
function renderCalendar(){const y=state.month.getFullYear(),m=state.month.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0),q=normalize($("#calendar-search")?.value);$("#month-label").textContent=new Intl.DateTimeFormat("es-PE",{month:"long",year:"numeric"}).format(first);let h=["Lun","Mar","Mié","Jue","Vie","Sáb","Dom"].map(n=>`<div class="day-name">${n}</div>`).join("");for(let i=0;i<(first.getDay()+6)%7;i++)h+='<div class="day muted"></div>';for(let d=1;d<=last.getDate();d++){const key=`${y}-${String(m+1).padStart(2,"0")}-${String(d).padStart(2,"0")}`,items=state.shipments.filter(s=>s.fecha===key&&matchesShipment(s,q));h+=`<div class="day ${items.length?"has-shipment":""}"><div class="num">${d}</div>${items.slice(0,3).map(s=>{const c=clientById(s.clientId)||{},label=`${c.razon||"Cliente"}${s.serie?` · ${s.serie}`:""}`;return `<button class="event" title="${esc(label)}" data-action="open-client" data-id="${c.id}">${esc(label)}</button>`;}).join("")}${items.length>3?`<div class="more">+${items.length-3} más</div>`:""}</div>`;}$("#calendar-grid").innerHTML=h;const prefix=`${y}-${String(m+1).padStart(2,"0")}`,monthItems=state.shipments.filter(s=>s.fecha.startsWith(prefix)&&matchesShipment(s,q)).sort((a,b)=>a.fecha.localeCompare(b.fecha));$("#month-shipments").innerHTML=monthItems.map(s=>{const c=clientById(s.clientId)||{};return shipmentRow(s,c);}).join("")||'<div class="empty">No hay envíos que coincidan en este mes.</div>';}
function formatDate(v){if(!v)return"—";return new Intl.DateTimeFormat("es-PE",{day:"2-digit",month:"short",year:"numeric",timeZone:"UTC"}).format(new Date(`${v}T00:00:00Z`));}
render();
